name: Build

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4096M -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.caching=true"

jobs:
  build:
    name: Build & publish release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare release APK
        uses: ././github/actions/prepare-apk
        with:
          build-type: release

# todo: To be finished later